from VLCwebsite.settings import *

DEBUG = TEMPLATE_DEBUG = False
PYBB_DISABLE_NOTIFICATIONS = False
PYBB_DISABLE_SUBSCRIPTIONS = True

#CSRF_COOKIE_SECURE = True
#SESSION_COOKIE_SECURE = True

CONN_MAX_AGE = 60
